version: '3'

services:
  database:
    image: 'postgres:15.3'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    networks:
      - postgres-network
    volumes:
      - /var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  postgres-network:
    driver: bridge